version: '3.9'

services:
  docking:
    build:
      context: .
      dockerfile: .docker/octane.Dockerfile
    volumes:
      - app_storage:/var/www/html/storage/app
    networks:
      - coolify
    depends_on:
      - gotenberg
    ports:
      - '8888:80'
      - '8081:8080'

  gotenberg:
    build:
      context: .
      dockerfile: .docker/gotenberg.Dockerfile
    networks:
      - coolify
    ports:
      - '9898:3000'

networks:
  coolify:
    external: true # Use the existing Coolify network

volumes:
  app_storage:
